import { ARTIFACT_IMAGES } from "./data";
import { ChronicleArtifact } from "./types";

export const SEEDED_PROJECTS: ChronicleArtifact[] = [
  {
    id: "prj-1",
    code: "PRJ-001",
    name: "AROHAN- Autonomous Safety Monitoring System",
    description: "AROHAN is a real-time, multi-modal IoT safety monitoring system and emergency response ecosystem. It utilizes physical hardware (ESP32-CAM, Arduino rover, gas/smoke/motion sensors) integrated with an AI engine that performs sensor fusion and hazard severity scoring (Low to Critical). It features a Flask-based Computer Vision backend for face recognition and hazard detection, a scalable React/Vite dashboard for monitoring, Firebase Realtime Database for state management, and Twilio for automated WhatsApp/Voice alerts. It is designed to autonomously dispatch a rover for visual verification of hazardous environments before human intervention is required.\\n\\n**Status**: The project is currently production-ready and fully prepared for open-source contributions. The core architecture (React frontend, Python/Flask CV backend, Firebase integration, AI scoring engine, and Arduino/ESP32 IoT scripts) is fully implemented and tested. We recently completed a major repository restructure, implementing clean architecture, comprehensive setup/API documentation, GitHub Actions CI pipelines, issue templates, and contribution guidelines. It is actively maintained and ready to welcome new contributors for the Summer of Code.\\n\\n**Repository**: [GitHub Link](https://github.com/shaddy-pv/Arohan)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.column,
    loadIndex: 51,
    purityIndex: 86,
    cyberMeshLevel: 9,
    archivist: "Md Shadan Siddiqui",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-2",
    code: "PRJ-002",
    name: "CO₂ Detection from Hyperspectral Imagery using AVIRIS Data",
    description: "This repository presents a comprehensive MATLAB framework for the detection, visualization, and statistical analysis of atmospheric CO₂ signatures using the Airborne Visible/Infrared Imaging Spectrometer (AVIRIS) hyperspectral imagery.\n\nDeveloped as part of the MATLAB and Simulink Challenge, the project implements a progressive spectral conditioning pipeline that sequentially combines four complementary algorithms:\n\nContinuum Interpolated Band Ratio (CIBR)\nJoint Reflectance and Gas Estimator (JRGE)\nSpectral Fitting Algorithm (SFA)\nCluster-Tuned Matched Filter (CTMF)\nInstead of relying on a single detector, the framework treats CO₂ retrieval as a sequence of spectral conditioning operations aimed at suppressing background variability and refining localized anomaly responses.\\n\\n**Status**: While core data ingestion works, the system suffers from stability issues regarding missing data, lacks environmental compensation formulas, and requires a code refactor to remove hardcoded parameters before deployment. The co2-detection-matlab project aims to build a robust data processing pipeline to ingest, clean, analyze, and visualize carbon dioxide (CO_2) levels from remote sensor logs. The foundational algorithms for importing data and plotting basic trends are complete. However, the project is currently blocked from production-level testing due to critical edge-case bugs (data dropouts causing crashes) and algorithmic inaccuracies stemming from a lack of sensor drift compensation.\\n\\n**Repository**: [GitHub Link](https://github.com/vibhorjoshi/co2-detection-matlab)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.castle,
    loadIndex: 33,
    purityIndex: 86,
    cyberMeshLevel: 7,
    archivist: "vibhor joshi",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-3",
    code: "PRJ-003",
    name: "DriveLegal",
    description: "DriveLegal India is a web application that provides citizens with location-specific traffic law information, fine schedules, and an automated challan calculator covering all 28 states and 8 Union Territories of India.\nAll data is embedded directly in the application — no external APIs, no internet connection required after installation.\\n\\n**Status**: I want to implement more features and additions to this project and let the contributors work in AutuTech Category\\n\\n**Repository**: [GitHub Link](https://github.com/mudit108-code/Drive-Legal)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.athena,
    loadIndex: 86,
    purityIndex: 71,
    cyberMeshLevel: 6,
    archivist: "Mudit Khater",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-4",
    code: "PRJ-004",
    name: "THRIVO",
    description: "Thrivo is a horizontal ecosystem designed to solve \"founder tool fatigue\" by unifying the startup journey end-to-end. It seamlessly connects builders (founders), marketers (creators), funders (investors), and buyers (consumers) under one roof.\\n\\n**Status**: Active Development\\n\\n**Repository**: [GitHub Link](https://github.com/Ambixion-Corp/thrivo-frontend)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.socrates,
    loadIndex: 64,
    purityIndex: 91,
    cyberMeshLevel: 8,
    archivist: "Navin Rai",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-5",
    code: "PRJ-005",
    name: "Thrivo",
    description: "Backend for Thrivo\\n\\n**Status**: Active developement\\n\\n**Repository**: [GitHub Link](https://github.com/Ambixion-Corp/thrivo-backend)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.hephaestus,
    loadIndex: 41,
    purityIndex: 94,
    cyberMeshLevel: 5,
    archivist: "Aashim Ahamed",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-6",
    code: "PRJ-006",
    name: "AstraGuard-AI",
    description: "AstraGuard AI is an open-source, mission-critical security system designed specifically for CubeSat and satellite operations. It seamlessly combines AI-assisted threat detection with practical offensive security tooling to create a comprehensive defense platform for space systems.\n\nAt its core, AstraGuard AI is:\n\nA Security Platform: Built to test applications against simulated threats in controlled environments\nAn AI Learning System: Uses local LLMs (Llama 3/Mistral) to analyze attack surfaces and generate smart payloads\nA Monitoring Dashboard: Provides real-time visualization of security posture and system health\nA Training Ground: Designed to help learners bridge the gap between theoretical knowledge and real-world security workflows\\n\\n**Status**: active\\n\\n**Repository**: [GitHub Link](https://github.com/AstraGuard-AI/AstraGuard-AI-ISOC-26)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.aristotle,
    loadIndex: 78,
    purityIndex: 81,
    cyberMeshLevel: 3,
    archivist: "Subhajit Roy",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-7",
    code: "PRJ-007",
    name: "Automatic Detect radar system",
    description: "Ardiuno uno, Processing software for Graphics representation, AC servo motor,\\n\\n**Status**: Working\\n\\n**Repository**: [GitHub Link](https://www.linkedin.com/in/masoom-kumar-197257286)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.atlas,
    loadIndex: 51,
    purityIndex: 71,
    cyberMeshLevel: 3,
    archivist: "Masoom Kumar",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-8",
    code: "PRJ-008",
    name: "ShikshaSathi",
    description: "ShikshaSathi is a voice-first AI co-teacher built for Indian school classrooms. A teacher speaks or types a topic, and the system instantly generates a complete, grade-appropriate lesson in Hindi, English or Hinglish, complete with visuals, quizzes, classroom activities, and an AI-generated narration. It runs on smart boards, works offline, and supports multilingual teaching across all subjects.\\n\\n**Status**: Core features are functional and deployed, including AI lesson generation, quizzes, visual learning, summaries, translations, and voice interactions. Current development focuses on prompt optimization, improving diagram/flowchart visuals, refining content quality, and polishing the UI/UX. The project is in a working MVP stage and requires final enhancements for production-scale deployment and broader classroom adoption.\\n\\n**Repository**: [GitHub Link](https://github.com/harshitSingh1/ShikshaSathi)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.ares,
    loadIndex: 38,
    purityIndex: 76,
    cyberMeshLevel: 9,
    archivist: "Harshit Singh",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-9",
    code: "PRJ-009",
    name: "Automaintainer",
    description: "An Always-On Autonomous AI Software Engineering Team built with LangGraph, FastAPI, and Next.js that operates natively within your GitHub repositories.\\n\\n**Status**: Active Development\\n\\n**Repository**: [GitHub Link](https://github.com/PxA-Labs/AutoMaintainer)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.prometheus,
    loadIndex: 54,
    purityIndex: 98,
    cyberMeshLevel: 9,
    archivist: "Purvansh Joshi",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-10",
    code: "PRJ-010",
    name: "interpretable-regulatory-genomics",
    description: "Interpretable machine learning system for discovering hidden regulatory switches in non-coding DNA using ENCODE genomic data. Optimized for resource-constrained, reproducible research.\\n\\n**Status**: Active Development and Testing\\n\\n**Repository**: [GitHub Link](https://github.com/PxA-Labs/interpretable-regulatory-genomics)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.neuralLattice,
    loadIndex: 38,
    purityIndex: 98,
    cyberMeshLevel: 4,
    archivist: "Purvansh Joshi",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-11",
    code: "PRJ-011",
    name: "Bio-Sentinel: An AI-Driven Preventive Health Monitoring and Disease Outbreak Prediction System Using Environmental Intelligence",
    description: "Bio-Sentinel is a kind of intelligent, preventive healthcare platform  designed to forecast disease risks and possible outbreaks, before they turn into serious public health emergencies. It is a bit different from the conventional healthcare systems, because those usually concentrate on identifying and handling diseases only after symptoms show up. Bio-Sentinel takes a more proactive style, like continuously checking environmental conditions, personal health info, and disease surveillance indicators, so health risks can be caught at an earlier stage.\n\nThe platform also pulls in several streams of real time data, such as weather parameters, air quality, pollen amounts, rainfall patterns, humidity and temperature, plus geospatial context, and even user health profiles. All these separate and varied datasets get brought together into one analytical method, which helps the system figure out how shifts in the outdoors can affect disease spread, and also the specific health outcomes for individuals. Then, by mixing environmental intelligence with artificial intelligence and machine learning, Bio-Sentinel turns raw environmental signals into useful health insights, and finally into personalized preventive suggestions.\n\nAt the core of the system there is this stacked ensemble machine learning set up, built from Random Forest, XGBoost, LightGBM, and then a Logistic Regression meta-learner kind of thing. Overall, it looks at more than fifty environmental plus health-related features, to predict diseases like Dengue, Malaria, Influenza, Heat Stroke, Common Cold, Migraine, Stroke, Heart Attack, Sinusitis, Arthritis, and Eczema, and yeah it does so with high predictive performance. Also, beyond just individual disease prediction, Bio-Sentinel brings in a climate-aware disease outbreak prediction approach that blends statistical anomaly detection with environmental risk multipliers, so it can flag possible outbreaks before large scale community transmission starts happening, which is kinda the whole point.\n\nThere’s more, the platform also uses Geographic Information System (GIS) analytics to dig up hyper-local disease and environmental risk hotspots. By looking at elevation data, drainage infrastructure, weather conditions, plus the spatial analysis side of things, Bio-Sentinel produces location specific risk maps. These maps then help healthcare authorities and disaster management agencies plan targeted interventions, and manage resources more efficiently. In practice, it means a quicker emergency response when climate-related events show up, like floods, or those disease outbreaks that spread faster than people expect.\n\nTo improve accessibility and the overall user experience, Bio-Sentinel has an AI-powered health helper that makes health reports easier to read, clarifies disease risks, answers user questions, and offers preventive steps grounded in evidence. This assistant stitches together environmental awareness , machine learning predictions , user health profiles, and knowledge from research-based sources, so it can give guidance that feels contextual and personal. Then the smart notification services keep watch for environmental shifts and will automatically notify users about heat waves, bad air quality , flood related health risks , mosquito borne disease threats, and other new hazards that show up over time.\n\nBio-Sentinel also tries to fill a real gap between environmental monitoring and public health, basically by moving care away from a reactive “treat after it happens” style and toward a preventive intelligence approach. The platform is useful for individuals, hospitals, public health agencies , municipal authorities, and disaster management organizations. It helps with early risk detection, supports more informed decisions, improves how healthcare is planned ahead of time, and strengthens community resilience in practical ways. By bringing environmental intelligence, machine learning , disease surveillance , geospatial analytics, explainable AI, and personalized healthcare into one ecosystem, Bio-Sentinel becomes a scalable, innovative option for climate resilient healthcare and what people often call next generation public health monitoring.\\n\\n**Status**: Bio-Sentinel is currently in the working prototype (Minimum Viable Product - MVP) stage. The platform has been successfully developed with a fully functional frontend and backend was on railway and now all backend went down so need to configure and fix overall backend system\\n\\n**Repository**: [GitHub Link](https://github.com/gaur-avvv/Bio-SentinelX)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.gildedGuardian,
    loadIndex: 33,
    purityIndex: 91,
    cyberMeshLevel: 4,
    archivist: "Gaurav Singh",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-12",
    code: "PRJ-012",
    name: "Threat Incident Management System",
    description: "Threat Incident Management System is a full-stack web application designed to help organizations securely report, manage, search, and monitor security-related incidents through a centralized dashboard.\n\nThe system provides secure user authentication using JWT, role-based access control for Analysts and Administrators, advanced incident search powered by Elasticsearch, and an interactive React dashboard for efficient incident management. It also includes automated risk score calculation based on incident severity and category, enabling organizations to prioritize critical threats effectively.\n\nThe project follows a modern microservice-ready architecture with a Spring Boot REST API backend, React frontend, MongoDB for data storage, Elasticsearch for full-text search, and Docker Compose for simplified deployment.\n\nKey Features -\nSecure JWT Authentication\nRole-Based Access Control (Admin & Analyst)\nIncident CRUD Operations\nFull-Text Search using Elasticsearch\nAutomatic Risk Score Calculation\nDashboard Statistics & Analytics\nRESTful API Architecture\nDockerized Development Environment\nGitHub Actions CI/CD Integration\nResponsive React Dashboard\n\nTech Stack -\nBackend: Spring Boot 3.3.5, Java 21\nFrontend: React 19, Vite\nDatabase: MongoDB 7\nSearch Engine: Elasticsearch 8.12\nAuthentication: JWT\nContainerization: Docker & Docker Compose\nCI/CD: GitHub Actions\nBuild Tool: Maven\\n\\n**Status**: The project is currently in the advanced development stage and includes a fully functional backend REST API, React-based frontend dashboard, secure JWT authentication, role-based authorization, MongoDB integration, Elasticsearch-powered search, Dockerized infrastructure, and automated CI/CD using GitHub Actions.  Current functionality includes user authentication, incident management, dashboard statistics, risk score calculation, and full-text search. Future enhancements include real-time notifications, audit logging, file attachment support, email alerts, analytics dashboards, and cloud deployment.\\n\\n**Repository**: [GitHub Link](https://github.com/Pranav-0440/threat-incident-management)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.valerius,
    loadIndex: 84,
    purityIndex: 80,
    cyberMeshLevel: 3,
    archivist: "Ghorpade Pranav Babasaheb",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-13",
    code: "PRJ-013",
    name: "AROHAN- Autonomous Safety & Hazard Monitoring System",
    description: "AROHAN is an open-source, AI and IoT-powered autonomous safety monitoring system designed for real-time hazard detection and intelligent emergency response in industrial, laboratory, campus, and other safety-critical environments.\n\nThe system combines IoT sensor nodes, computer vision, an autonomous ESP32-based rover, AI-driven multi-modal hazard analysis, and a real-time web dashboard. It monitors environmental and visual parameters such as fire, smoke, gas, air quality, temperature, motion, and camera feeds to detect potential hazards, assess their severity, generate alerts, and support autonomous inspection of affected areas.\n\nThe project follows a multi-layer architecture consisting of a React + TypeScript monitoring dashboard, Python/Flask computer-vision services, Firebase for real-time cloud communication, ESP32/ESP32-CAM hardware, rover control systems, and AI-based sensor-fusion and hazard-analysis modules.\n\nAs an open-source project, AROHAN provides meaningful contribution opportunities across AI/ML, computer vision, full-stack development, IoT and embedded systems, cloud integration, testing, simulations, documentation, and system optimization. The goal during IEEE Summer of Code 2026 is to evolve AROHAN into a more modular, reliable, contributor-friendly and extensible open-source safety platform through structured development milestones and community contributions.\\n\\n**Status**: Prototype is Ready this is the Video link- https://drive.google.com/file/d/1I-GsaEnuhVUpobU__CI98upZ1kNSIQ63/view?usp=sharing\\n\\n**Repository**: [GitHub Link](https://github.com/shaddy-pv/Arohan)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.column,
    loadIndex: 59,
    purityIndex: 82,
    cyberMeshLevel: 5,
    archivist: "Md Shadan Siddiqui",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-14",
    code: "PRJ-014",
    name: "Image to Biomass Prediction",
    description: "Developed a deep learning model to estimate pasture biomass from aerial RGB images for the CSIRO Image2Biomass Challenge. Built and trained convolutional neural networks (including Attention U-Net/CNN architectures) using PyTorch, applying data augmentation, custom loss functions, and learning rate scheduling to improve prediction accuracy. Performed data preprocessing, model evaluation, and hyperparameter tuning to optimize performance, enabling accurate biomass estimation for precision agriculture and sustainable land management.\\n\\n**Status**: Mid level algo ready\\n\\n**Repository**: [GitHub Link](https://github.com/devansh1219/CSIRO-Image2Biomass_Prediction)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.castle,
    loadIndex: 41,
    purityIndex: 85,
    cyberMeshLevel: 5,
    archivist: "Devansh Chandna",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-15",
    code: "PRJ-015",
    name: "CTFd Self-Hosted CTF Platform for IEEE HIT SB",
    description: "Deployed and administered a self-hosted CTFd instance for a live Capture-the-Flag event, handling ~30 concurrent participants over ngrok tunneling from a personal machine, with load-testing via Apache Bench up to 50 concurrent users.\\n\\n**Status**: Completed and successfully run live; documented setup could be extended into a reusable open-source CTF hosting template.\\n\\n**Repository**: [GitHub Link](https://github.com/Crusader-Boss/CTFD-platdform-for-IEEE-HIT-SB)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.athena,
    loadIndex: 62,
    purityIndex: 83,
    cyberMeshLevel: 3,
    archivist: "Kshitij Arya",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-16",
    code: "PRJ-016",
    name: "Pahadistay-AI",
    description: "PahadiStay AI is an AI-powered full-stack web platform that connects travelers with local Himalayan homestays through personalized recommendations and smart trip planning. The platform enables users to discover, book, and review homestays while providing hosts with tools to manage listings and bookings. Built using React.js, Node.js, Express.js, MongoDB, and Google Gemini API, the project promotes sustainable tourism and serves as a collaborative open-source project for contributors in frontend, backend, AI, and documentation.\\n\\n**Status**: In Development - Core modules, authentication, and frontend are implemented. AI-powered recommendations, booking features, and additional functionalities are currently under active development and testing.\\n\\n**Repository**: [GitHub Link](https://github.com/iamsonaliu/PahadiStay-AI)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.socrates,
    loadIndex: 81,
    purityIndex: 71,
    cyberMeshLevel: 4,
    archivist: "Sonali Upadhyay",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-17",
    code: "PRJ-017",
    name: "MedMind_RAG",
    description: "MedMind is a production-grade RAG-based (Retrieval-Augmented Generation) medical knowledge assistant. It ingests 40+ medical textbooks as its knowledge base and uses a hybrid retrieval pipeline combining BM25 and vector search, with cross-encoder reranking for relevance, and LLaMA 3.3 70B (via Groq) as the generation model. The stack is built on FastAPI and ChromaDB.\\n\\n**Status**: completed\\n\\n**Repository**: [GitHub Link](https://github.com/DarshanaDDevi/Medmind-RAG)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.hephaestus,
    loadIndex: 84,
    purityIndex: 85,
    cyberMeshLevel: 3,
    archivist: "Darshana D Devi",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-18",
    code: "PRJ-018",
    name: "DonarChain",
    description: "DonarChain is a blockchain-based blood donation platform developed to make the blood donation process transparent, secure, and efficient. The application allows donors to register, hospitals and blood banks to manage blood inventory, and recipients to raise blood requests while maintaining a trusted record of every donation.\n\nThe frontend was built using React.js and Tailwind CSS to provide a responsive and intuitive user interface. The backend was developed with Node.js and Express.js, which handle user authentication, blood requests, inventory management, and communication with the blockchain. MongoDB is used to store user profiles, hospital information, blood inventory, and other off-chain data for faster access. Solidity was used to develop smart contracts deployed on the Ethereum blockchain, ensuring that donation records remain immutable and tamper-proof. Ethers.js/Web3.js enables interaction between the web application and the smart contracts, while MetaMask is used for wallet authentication and transaction signing. The project was managed using Git and GitHub for version control and collaboration.\\n\\n**Status**: Currently in the prototype/MVP stage. The core features, including user authentication, donor registration, blood request management, hospital and blood bank modules, and blockchain-based donation record storage, have been implemented. The project is being tested and refined with a focus on improving scalability, security, and user experience before deployment.\\n\\n**Repository**: [GitHub Link](https://github.com/Pawan-git05/Donarchain)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.aristotle,
    loadIndex: 68,
    purityIndex: 95,
    cyberMeshLevel: 8,
    archivist: "Pawan Singh",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-19",
    code: "PRJ-019",
    name: "Laughify",
    description: "So laughify is web game .We see very time people doing no laugh challenges and trends etc.I made an web game using mediapipe face mesh model which detects you laugh while a funny meme will be playing on you screen in web game\\n\\n**Status**: So status of project is good .A basic prototype is ready and still has best experiences who used it.Main tagline of game is we bring smile on your face.  Live Link:  https://laughify-y41f.onrender.com\\n\\n**Repository**: [GitHub Link](https://github.com/ANKUR172006/Laughify)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.atlas,
    loadIndex: 66,
    purityIndex: 88,
    cyberMeshLevel: 5,
    archivist: "ANKUR",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-20",
    code: "PRJ-020",
    name: "GestureStage — Real-Time Gesture-Controlled 3D Presentation Engine",
    description: "GestureStage reimagines how presentations are delivered — replacing the mouse/clicker with real-time hand-gesture control over a fully interactive 3D presentation space, built on MediaPipe for hand-tracking and Three.js/Vite for rendering. Unlike static slide decks, GestureStage renders content in a navigable 3D environment where gestures control camera movement, object manipulation, and slide transitions — making it suited for live demos, product pitches, and hardware showcases where touch-free, spatial interaction adds real impact.\nThe core technical challenge is building gesture recognition that's robust and low-latency enough for live use: reliable detection across different hand sizes, lighting conditions, and camera angles, without introducing lag that breaks the presenter's flow. Beyond the working core, the project opens into substantial engineering work: expanding the gesture vocabulary without ambiguity/misfires, building a plugin architecture so developers can define custom gestures and 3D behaviors, adding multi-user/collaborative control for remote presentations, and creating accessibility fallbacks (voice + gesture hybrid control) for users who can't rely on hand tracking alone. Each of these is an independently scoped problem — not a bolt-on feature.\\n\\n**Status**: The core pipeline is functional — real-time hand-gesture recognition using MediaPipe is integrated with 3D slide rendering and navigation built on Three.js/Vite. Right now I'm working on improving gesture detection accuracy across different lighting conditions and hand sizes, and reducing recognition latency for smoother live use. Next on my list is building out a wider gesture vocabulary and adding basic multi-user support.\\n\\n**Repository**: [GitHub Link](https://github.com/dianoK-c)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.ares,
    loadIndex: 67,
    purityIndex: 90,
    cyberMeshLevel: 7,
    archivist: "Anushka",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-21",
    code: "PRJ-021",
    name: "fiscal pilott",
    description: "Fiscal Pilot is a next-generation financial technology platform designed to democratize high-level financial strategy for early-stage startups. By replacing the need for an expensive, traditional Chief Financial Officer, Fiscal Pilot leverages artificial intelligence to help founders navigate financial turbulence, optimize cash flow, and scale with confidence.\n\nIt transforms raw financial data into actionable strategic insights, ensuring startups are always investor-ready.\n\nCore Value Proposition & Potential Features\n\nReal-Time Runway & Burn Rate Tracking: Automated dashboards that constantly monitor cash flow, giving founders an immediate, clear picture of their financial health without manual spreadsheet updates.\n\nIntelligent Scenario Planning: AI-driven forecasting that allows founders to stress-test their business models. (e.g., \"What happens to our runway if we hire three new developers in Q3 or if our CAC increases by 15%?\")\n\nAutomated Investor Reporting: Seamlessly generates clean, professional financial reports and pitch-deck-ready data visualizations, making board meetings and fundraising rounds significantly less stressful.\n\nExpense & Capital Optimization: Algorithms that analyze spending patterns to identify wasted capital and recommend areas for cost reduction.\\n\\n**Status**: Digital CFO\\n\\n**Repository**: [GitHub Link](https://github.com/Aayushsingh16/fiscal-pilotiuiuiuiiiiiiiii)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.prometheus,
    loadIndex: 45,
    purityIndex: 79,
    cyberMeshLevel: 9,
    archivist: "Aayush Singh",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-22",
    code: "PRJ-022",
    name: "QuizSphere",
    description: "QuizSphere is an open-source online assessment platform built using the MERN stack. Originally developed as a college academic project, it is now being enhanced into a community-driven platform for secure and scalable online examinations. The platform supports role-based authentication, quiz creation and scheduling, automated evaluation, performance analytics, and responsive user interfaces. Its modular architecture and clear documentation make it suitable for collaborative open-source development.\\n\\n**Status**: The project is in active development. Core modules have been implemented, and current work focuses on improving documentation, code quality, UI/UX, and adding new features to prepare the project for open-source contributions.\\n\\n**Repository**: [GitHub Link](https://github.com/SauravPandey56/QuizApplication/tree/main)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.neuralLattice,
    loadIndex: 32,
    purityIndex: 95,
    cyberMeshLevel: 9,
    archivist: "saurav pandey",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-23",
    code: "PRJ-023",
    name: "AI-Based Career Prediction System Using Machine Learning",
    description: "The AI-Based Career Prediction System is a Machine Learning-based web application that helps students identify suitable career paths based on their academic performance, skills, and interests. The system collects inputs such as academic marks, mathematics score, logical thinking ability, communication skills, Python programming skills, and interest in AI and business. A Decision Tree Classifier trained using Scikit-learn analyzes these inputs and predicts the most appropriate career option.\n\nThe application is built using Python Flask for the backend, HTML, CSS, and JavaScript for the frontend, and Pandas for data processing. The trained model is saved using Joblib and integrated with the Flask application to provide real-time predictions. The project features a modern, responsive user interface and is deployed online using Vercel, with source code managed through GitHub. The system aims to guide students in making informed career decisions using Artificial Intelligence and Machine Learning.\\n\\n**Status**: The project is currently in the working prototype stage. The Machine Learning model has been developed using a Decision Tree Classifier and integrated with a Flask backend. The frontend provides a responsive user interface for entering student details and viewing career predictions. Core features such as data processing, model prediction, and user interaction have been implemented. The project has been deployed on Vercel for online access. Future improvements include adding more career options, improving prediction accuracy with larger datasets, implementing user authentication, and providing personalized career guidance and learning recommendations.\\n\\n**Repository**: [GitHub Link](https://github.com/thepranavugale/career-predictor)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.gildedGuardian,
    loadIndex: 41,
    purityIndex: 87,
    cyberMeshLevel: 3,
    archivist: "Pranav Sunil Ugale",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-24",
    code: "PRJ-024",
    name: "Grid Shield",
    description: "GridShield is an AI-powered cyber-physical intrusion detection and resilience platform designed to secure smart power grids against modern cyber threats. The system continuously monitors network traffic and electrical telemetry to detect attacks such as False Data Injection (FDIA), spoofing, and anomalous behavior in real time. By combining machine learning, secure network verification, packet analysis, and sensor validation, GridShield provides early threat detection, automated risk assessment, and rapid incident response while ensuring the reliability and stability of critical power infrastructure.\\n\\n**Status**: GridShield has successfully progressed from the conceptual phase to a functional prototype. The system integrates AI-based anomaly detection with real-time cyber-physical monitoring to identify suspicious network traffic and abnormal electrical telemetry in smart power grids. Core modules, including secure network verification, packet analysis, telemetry validation, and the monitoring dashboard, have been implemented and tested in a controlled environment. The prototype demonstrates real-time threat detection, automated alert generation, and resilience against simulated cyberattacks such as False Data Injection (FDIA) and network anomalies. The project has also been documented through a research paper and validated in national innovation and hackathon platforms, showcasing its feasibility as a scalable cybersecurity solution for critical power infrastructure.\\n\\n**Repository**: [GitHub Link](https://github.com/Parth-Sidhapura/GridShield)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.valerius,
    loadIndex: 53,
    purityIndex: 82,
    cyberMeshLevel: 9,
    archivist: "PARTH SIDHAPURA",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-25",
    code: "PRJ-025",
    name: "Ai enabled recommendation engine for an e-commerce platform",
    description: "Using Ai we can give the suggestions for tje customers based on their interest in an shopping app\\n\\n**Status**: I have builded bit yet to deploy with more accuracy working on it..\\n\\n**Repository**: [GitHub Link](https://github.com/saisaran777)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.column,
    loadIndex: 70,
    purityIndex: 85,
    cyberMeshLevel: 6,
    archivist: "SAI SARAN H A",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-26",
    code: "PRJ-026",
    name: "EchoShield: AI-Powered Detection of Adversarial Attacks on Voice Models",
    description: "With the rapid adoption of voice-based artificial intelligence in virtual assistants, banking systems, healthcare, smart homes, and biometric authentication, speech recognition models have become an integral part of modern digital ecosystems. However, these models are highly vulnerable to adversarial audio attacks, where attackers intentionally manipulate voice signals by introducing subtle perturbations that are often imperceptible to humans but sufficient to deceive machine learning models. Such attacks can force a voice assistant to execute unauthorized commands, bypass speaker authentication systems, manipulate speech-to-text outputs, or compromise sensitive information. Existing speech recognition systems primarily focus on improving accuracy and user experience, while comparatively little attention has been given to detecting whether an incoming audio sample has been maliciously crafted. As voice AI becomes increasingly prevalent in security-critical applications, there is an urgent need for intelligent systems capable of identifying adversarial audio before it reaches the speech recognition model.\n\nThe proposed system, **EchoShield**, addresses this challenge by acting as an intelligent security layer that analyzes incoming voice samples and determines whether they are genuine or adversarial before forwarding them to the target voice model. Instead of replacing existing speech recognition systems, EchoShield functions as a protective detection framework that continuously monitors audio inputs using advanced signal processing and deep learning techniques. The system extracts multiple acoustic and spectral features, including Mel-Frequency Cepstral Coefficients (MFCCs), spectrograms, chroma features, spectral contrast, and temporal characteristics, which are then analyzed using a hybrid deep learning architecture combining Convolutional Neural Networks (CNNs) for spatial feature extraction and Long Short-Term Memory (LSTM) networks for capturing temporal dependencies within speech signals. Based on these learned patterns, the model classifies whether an audio sample is authentic or contains adversarial manipulations. If malicious characteristics are detected, the audio is blocked, flagged, and logged for further analysis, thereby preventing the underlying voice recognition model from processing potentially harmful inputs.\n\nCurrent approaches for defending speech recognition systems mainly involve adversarial training, input preprocessing, denoising techniques, or robustness improvements to the speech recognition model itself. Although these methods increase resilience against specific attack techniques, they often require retraining large speech models, incur significant computational overhead, and perform poorly against newly emerging attack methods. Furthermore, many existing solutions are tailored to known attack patterns and struggle to generalize across different adversarial generation techniques. They also provide limited explainability regarding why an input was classified as malicious, making deployment in high-security environments more challenging.\n\nThe novelty of EchoShield lies in its model-agnostic detection framework that operates independently of the underlying speech recognition system. Rather than modifying or retraining the target voice model, EchoShield serves as an external defensive layer capable of protecting multiple voice AI applications using the same detection pipeline. The proposed framework combines deep acoustic feature extraction with explainable AI techniques to identify subtle perturbations introduced during adversarial attacks while remaining adaptable to unseen attack strategies. By separating the detection mechanism from the speech recognition model, the solution improves scalability, simplifies deployment, and allows organizations to enhance security without altering existing production systems. Additionally, the framework maintains detailed security logs, confidence scores, and attack classifications, enabling continuous monitoring and forensic analysis.\n\nThe overall architecture consists of six major components that work together to secure voice-based AI systems. Initially, an audio sample is captured through a microphone or uploaded by the user and passes through an audio preprocessing module responsible for noise reduction, normalization, silence removal, and feature extraction. The processed features are then forwarded to the adversarial detection engine, where the hybrid CNN-LSTM model analyzes both spectral and temporal characteristics to distinguish between legitimate and manipulated audio samples. The prediction engine generates a confidence score indicating the likelihood of an adversarial attack. A decision module then determines whether the audio should be accepted or rejected. If the sample is classified as safe, it is forwarded to the target Automatic Speech Recognition (ASR) or speaker verification model. Otherwise, the system blocks the request, records detailed logs within the monitoring database, and generates alerts for administrators. This layered architecture enables EchoShield to provide real-time, scalable, and explainable protection against adversarial attacks, significantly improving the security and trustworthiness of modern voice AI systems.\\n\\n**Status**: The project is currently in the Research and Design (R&D) phase. Extensive research has been conducted to understand the latest adversarial attack techniques targeting voice AI systems, including attacks on speech recognition and speaker verification models. A comprehensive literature review has been completed, and the problem statement, objectives, proposed methodology, system architecture, technology stack, and implementation roadmap have been finalized. Relevant datasets and machine learning approaches have also been evaluated to determine the most suitable solution for detecting adversarial audio. The development and implementation phase is scheduled to begin shortly, starting with dataset preparation, feature extraction, model development, and system integration. A GitHub repository will be created once the initial development is underway, and it will be updated regularly throughout the project's lifecycle to document progress, implementation, and experimental results.\\n\\n**Repository**: [GitHub Link](The project is currently in the Research and Design (R&D) phase. The literature review, problem analysis, solution design, system architecture, and technology selection have been completed. Development of the implementation is scheduled to begin shortly, and the GitHub repository will be created and made available as soon as the initial development phase starts.)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.castle,
    loadIndex: 89,
    purityIndex: 71,
    cyberMeshLevel: 7,
    archivist: "Rudraksh Sachdeva",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-27",
    code: "PRJ-027",
    name: "Vibe: Full Stack vibe coding platform with memory management and agent orchestration. Chatty: Full Stack chat and video calling app.  Sun: ML pipeline for detecting haalo CME events.",
    description: "1. Vibe is a vibe coding platform with memory management and agent orchestration capabilities.\n2. Chatty is a seamless chatting platform with video chat support.\n3. Sun is a pipeline designed to identify halo CME events from Solar Wind Ion Spectrometer (SWIS) Level-2 data aboard the Aditya-L1 mission.\\n\\n**Status**: All of the projects are totally complete and running properly, however I am building my startup called \"MeetMind AI\" and it's in prototyping phase.\\n\\n**Repository**: [GitHub Link](https://github.com/Ayush07737/vibe.git ,  https://github.com/Ayush07737/Chatty.git ,  https://github.com/Ayush07737/SUN.git)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.athena,
    loadIndex: 63,
    purityIndex: 74,
    cyberMeshLevel: 8,
    archivist: "Ayush Bhatt",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-28",
    code: "PRJ-028",
    name: "SwasthAshra – Intelligent Healthcare Management Platform",
    description: "SwasthAshra is a healthcare management platform designed to streamline hospital and clinic operations through intelligent automation. The project integrates patient registration, appointment scheduling, electronic health records, billing, pharmacy management, analytics, and administrative dashboards into a unified system. Its objective is to reduce operational inefficiencies, improve patient experience, and provide healthcare professionals with data-driven insights for better decision-making.\n\nThe project is designed with scalability and modularity in mind, making it suitable for community-driven development. Contributors can work on frontend and backend enhancements, healthcare analytics, security, API development, UI/UX improvements, testing, documentation, and deployment.\\n\\n**Status**: The project currently has a functional prototype with both frontend and backend modules implemented. Core healthcare workflows, including patient management, appointments, billing, and pharmacy services, are available. Future development will focus on expanding analytics, improving security and performance, enhancing accessibility, strengthening documentation, increasing automated test coverage, containerizing the application, and adding cloud deployment support. The repository will continue to evolve as an open-source project with clearly defined contribution opportunities for beginners and experienced contributors alike.\\n\\n**Repository**: [GitHub Link](https://github.com/vikasjha11/SwasthAshra)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.socrates,
    loadIndex: 31,
    purityIndex: 83,
    cyberMeshLevel: 8,
    archivist: "Vikas Kumar Jha",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-29",
    code: "PRJ-029",
    name: "Cricket Vision Intelligence System: AI-Powered Cricket Match Analysis using Computer Vision and Generative AI",
    description: "Cricket Vision Intelligence System is an AI-powered application that analyzes cricket match images to automatically identify key match events and generate intelligent insights. Using Computer Vision and Google's Gemini API, the system detects batting shots, bowling styles, player positions, field placements, and important moments from match images. It transforms visual match data into structured commentary, performance insights, and contextual analysis, making cricket analytics more accessible for players, coaches, analysts, and fans. The project focuses on image-based analysis without requiring video processing, ensuring faster inference and easier deployment.\\n\\n**Status**: The project is currently in active development. The core architecture, AI workflow, and image analysis pipeline have been implemented. Integration with the Gemini API for cricket image understanding and automated match analysis is complete, while improvements are ongoing to enhance prediction accuracy, user interface, and deployment. Upcoming features include advanced statistics visualization, multi-image match summarization, player performance tracking, and cloud deployment for public access.\\n\\n**Repository**: [GitHub Link](https://github.com/parth-khera/CRICKET_VISION_INTELL_SYSTEM_GDG)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.hephaestus,
    loadIndex: 67,
    purityIndex: 93,
    cyberMeshLevel: 7,
    archivist: "Parth Khera",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-30",
    code: "PRJ-030",
    name: "CareerLens AI – Intelligent Career Guidance and Skill Development Platform",
    description: "CareerLens AI is an AI-powered career guidance platform that helps students and early professionals make informed career decisions through personalized recommendations and learning roadmaps. The platform analyzes a user's skills, interests, education, and career goals to recommend suitable career paths, identify skill gaps, generate structured learning plans, and suggest portfolio projects and learning resources. By leveraging Large Language Models (Google Gemini), CareerLens AI delivers personalized guidance, making career planning more accessible, data-driven, and effective.\\n\\n**Status**: CareerLens AI is currently in the advanced development stage. The core backend APIs, AI integration, and personalized career recommendation workflow have been implemented successfully. The application can generate customized career roadmaps, analyze skill gaps, and recommend relevant learning resources based on user input. Ongoing development focuses on enhancing the user interface, implementing authentication, adding resume analysis and GitHub profile evaluation, improving scalability, and deploying the application for public access.\\n\\n**Repository**: [GitHub Link](https://github.com/sami1022/gemini_career-counselor)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.aristotle,
    loadIndex: 51,
    purityIndex: 73,
    cyberMeshLevel: 5,
    archivist: "Samiksha Sanjay Chandawar",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-31",
    code: "PRJ-031",
    name: "Soundwave",
    description: "transmission of sound without voice\\n\\n**Status**: in progress\\n\\n**Repository**: [GitHub Link](https://github.com/PxA-Labs/ultrasonic-phy-layer)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.atlas,
    loadIndex: 60,
    purityIndex: 91,
    cyberMeshLevel: 8,
    archivist: "Archit Mittal",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-32",
    code: "PRJ-032",
    name: "Patient Appoitnment Scheduling System",
    description: "manages patient time\\n\\n**Status**: almost done\\n\\n**Repository**: [GitHub Link](https://github.com/archittmittal/Patient-Appointment-Scheduling-System)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.ares,
    loadIndex: 31,
    purityIndex: 94,
    cyberMeshLevel: 7,
    archivist: "Archit Mittal",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-33",
    code: "PRJ-033",
    name: "Automatic Segregation Bio-medical Safety System",
    description: "Biomedical waste segregation is essential to prevent infection and contamination. This project uses AI, computer vision, and Arduino to identify medical waste such as needles, glass, and cotton, then automatically opens the correct disposal bin using servo motors. The system improves safety, hygiene, and reduces human intervention.\\n\\n**Status**: Biomedical waste management is a critical issue in healthcare environments due to the risks of infection and contamination caused by improper segregation of hazardous materials such as needles, glass, and cotton. Manual handling of such waste exposes healthcare workers to dangerous conditions and increases the chances of disease transmission. To address this problem, this project proposes an AI Powered Smart Healthcare Waste Segregation System that integrates computer vision and machine learning with an Arduino-based embedded system. A camera captures images of the waste, and a trained AI model classifies the objects into predefined categories, after which the classification result is sent to the Arduino to control servo motors that automatically open the appropriate disposal bin, enabling touchless and accurate segregation. The system is cost-effective, efficient, and reduces human intervention while improving safety and hygiene in medical environments. Furthermore, it has the potential for future enhancements such as improved AI accuracy, real-time processing, and IoT-based monitoring, making it a scalable solution for modern healthcare waste management.   give this upto 350 letters  Abstract (within ~350 characters):  Biomedical waste segregation is essential to prevent infection and contamination. This project uses AI, computer vision, and Arduino to identify medical waste such as needles, glass, and cotton, then automatically opens the correct disposal bin using servo motors. The system improves safety, hygiene, and reduces human intervention.     Today 2:56 PM Give abstract for this   Here's a simple and concise abstract (around 180–200 words) suitable for a mini project report:  Abstract  Biomedical waste management is an important part of healthcare because improper disposal of medical waste can spread infections and harm the environment. This project presents an AI-Powered Smart Healthcare Waste Segregation System that automatically identifies and separates biomedical waste using artificial intelligence and an Arduino-based control system. A camera captures the image of the waste item, and a trained AI model classifies it into categories such as needles, glass, or cotton. Based on the classification result, the Arduino controls a servo motor to open the appropriate waste bin automatically. This touchless process reduces direct human contact with hazardous waste, improving the safety of healthcare workers and maintaining better hygiene. The system is low-cost, easy to implement, and suitable for hospitals, clinics, and laboratories. It also minimizes errors in waste segregation and supports efficient biomedical waste management. In the future, the system can be enhanced with IoT technology for real-time monitoring and advanced AI models for higher classification accuracy. Overall, this project provides a smart, reliable, and scalable solution for safer and more efficient biomedical waste disposal in healthcare environments.\\n\\n**Repository**: [GitHub Link](https://github.com/suji187cf-pixel/AUTOMATIC-SEGREGATION-BIOMEDICAL-SAFETY-SYSTEM)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.prometheus,
    loadIndex: 30,
    purityIndex: 93,
    cyberMeshLevel: 7,
    archivist: "Sujitha M",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-34",
    code: "PRJ-034",
    name: "AgentScope",
    description: "AgentScope fills the gap: a lightweight, open-source, self-hosted observability dashboard for multi-agent AI pipelines.\\n\\n**Status**: in prroges\\n\\n**Repository**: [GitHub Link](https://github.com/archittmittal/AgentsScope)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.neuralLattice,
    loadIndex: 62,
    purityIndex: 73,
    cyberMeshLevel: 9,
    archivist: "Archit Mittal",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-35",
    code: "PRJ-035",
    name: "FairLens: Unified Fairness Auditing Framework with Metric Agreement Index (MAI) and EU AI Act Risk Mapping",
    description: "FairLens is in active development. Core architecture is implemented: dataset loaders for Adult/COMPAS/German Credit plus a synthetic generator with tunable bias, a canonical metric registry mapping AIF360 and Fairlearn implementations to shared fairness definitions, the Metric Agreement Index (MAI) as the core novel contribution, and EU AI Act Annex III risk-tier mapping. Currently consolidating two parallel implementation branches (a dataclass-based design and a flat DataFrame-based design) into a single coherent codebase before the next test pass. Target: arXiv (cs.LG) preprint ~November 2026, with a FAccT 2027 (Porto) submission planned.\\n\\n**Status**: In active development — core fairness-auditing pipeline and the novel Metric Agreement Index are implemented; consolidating architecture ahead of arXiv submission (target: Nov 2026).\\n\\n**Repository**: [GitHub Link](https://github.com/Priyalparmar03/FairLens-)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.gildedGuardian,
    loadIndex: 74,
    purityIndex: 84,
    cyberMeshLevel: 7,
    archivist: "Priyal Parmar",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-36",
    code: "PRJ-036",
    name: "Fintra AI – AI-Powered Personal Finance Platform",
    description: "Fintra AI is an open-source AI-powered personal finance platform designed to help users manage their income, expenses, budgets, and financial goals efficiently. The platform leverages Artificial Intelligence to provide personalized financial insights, smart budgeting recommendations, spending analytics, and interactive dashboards. The project is built with modern web technologies and is designed for contributors of all skill levels, offering opportunities in frontend, backend, AI, testing, documentation, and DevOps.\\n\\n**Status**: The project is under active development with the core architecture and primary modules implemented. Current features include user authentication, finance management, and dashboard development. Contributors will work on AI-powered financial recommendations, advanced analytics, UI/UX improvements, testing, documentation, and performance optimization. The project is structured with beginner-friendly issues and detailed documentation to ensure smooth onboarding for new contributors.\\n\\n**Repository**: [GitHub Link](https://github.com/Ashwinchauhan89/Fintra-AI)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.valerius,
    loadIndex: 86,
    purityIndex: 74,
    cyberMeshLevel: 3,
    archivist: "Ashwin Chauhan",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-37",
    code: "PRJ-037",
    name: "CampusClimb",
    description: "An NLP pipeline for organizing crowdsourced student notes across Operating Systems, Computer Networks and DBMS mapped to JNTUH syllabi. Employs a fine-tuned all-mpnet-base-v2 model (Clean-97 checkpoint) for semantic matching (~64.6% Top-1 / ~83% Top-3 accuracy), a dual-signal cosine+Jaccard deduplication method, and an empirical exam-frequency scoring system for PYQ importance. Currently writing up as a research paper for a Scopus indexed conference.\\n\\n**Status**: Active — core model and pipeline finalized, evaluation metrics locked (McNemar's test, bootstrap CIs confirmed). Research paper in final stages, targeting a Scopus-indexed conference submission.\\n\\n**Repository**: [GitHub Link](https://github.com/rahul05au/CampusClimb)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.column,
    loadIndex: 87,
    purityIndex: 78,
    cyberMeshLevel: 3,
    archivist: "Rahul Kumar",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-38",
    code: "PRJ-038",
    name: "Napoléon — AI-Powered Intelligent Web Crawler",
    description: "Napoléon is an intent-aware web crawler that combines hybrid crawling (HTTP + Selenium for JS-heavy sites) with an AI analysis layer — semantic relevance scoring, named entity extraction, keyword extraction (KeyBERT), and automatic summarization. It also includes a security scanner (XSS/SQLi vector detection, exposed secrets, sensitive files) and generates interactive network graphs of crawled pages and entities. Built as a modular Python pipeline with JSON/SQLite storage and report generation.\\n\\n**Status**: Feature-complete MVP on GitHub — full pipeline working end-to-end (crawling, AI analysis, security scanning, report/graph generation). Currently refining code and expanding test coverage.\\n\\n**Repository**: [GitHub Link](https://github.com/06-preetinder/napolean-web)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.castle,
    loadIndex: 70,
    purityIndex: 74,
    cyberMeshLevel: 4,
    archivist: "Preetinderjeet Singh",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-39",
    code: "PRJ-039",
    name: "FinOpsSentinel: Autonomous Cloud Cost Optimization & Orphan Resource Agent",
    description: "Cloud waste accounts for 20-35% of total cloud expenditure, primarily driven by orphaned resources like unattached storage disks and unassigned static IPs. FinOpsSentinel is an autonomous cloud agent developed in Python that scans Azure resource groups, extracts telemetry metadata, and applies AI reasoning to evaluate deletion risks. Featuring automated risk scoring and structured JSON reporting, FinOpsSentinel provides zero-human-intervention cloud governance while maintaining strict safety guardrails via dry-run execution modes.\\n\\n**Status**: FinOpsSentinel is currently in active development, with a working Proof-of-Concept (PoC) core engine already built and validated. The core architectural foundation—spanning cloud resource scanning, automated telemetry parsing, and structured audit reporting—is fully operational.\\n\\n**Repository**: [GitHub Link](https://github.com/Deepika0713/FinOpsSentinel)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.athena,
    loadIndex: 89,
    purityIndex: 99,
    cyberMeshLevel: 7,
    archivist: "Yeluri Deepika",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-40",
    code: "PRJ-040",
    name: "AccessLearn AI",
    description: "An inclusive, AI-powered Learning Management System (LMS) designed for users with visual and hearing impairments. Built with a lightweight Vanilla JS Single Page Application (SPA) architecture and Tailwind CSS, it utilizes Firebase for Auth and Firestore. Key features include a specialized Deaf Mode (subtitles, visual alerts), Blind/High Contrast Mode (Yellow-on-Black theme with Web Speech API narration), and AI-integrated learning tools like a contextual AI Doubt Solver tutor chat, automated note summaries, and interactive transcripts.\\n\\n**Status**: Currently we have made it as team as prototype with just 2 courses.we have to add ai assistant by placing real AI,some features for easy and simple user interface.\\n\\n**Repository**: [GitHub Link](https://github.com/PavaniSriBhuviPamidimukkala/AccesslearnAI)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.socrates,
    loadIndex: 77,
    purityIndex: 87,
    cyberMeshLevel: 8,
    archivist: "Pavani Sri Bhuvi Pamidimukkala",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-41",
    code: "PRJ-041",
    name: "AI-Powered Drought Prediction & Forecasting System",
    description: "A machine learning dashboard that predicts drought conditions in Eastern Uttar Pradesh, India using Standardized Precipitation Index (SPI). It employs an ensemble of MLP, SVR, Random Forest, and XGBoost models trained on ERA5 climate reanalysis data, featuring 5-year future forecasts (2026–2030), interactive Streamlit visualizations, and IMD monsoon deviation analytics.\n Live Demo: https:  //drought-prediction-xcbtufsrj5aqu9naaaldar.streamlit.app/\\n\\n**Status**: Completed with active enhancements. Core ML pipeline (preprocessing, training, evaluation, forecasting) is fully implemented. Streamlit dashboard is live. Ongoing work includes GRIB data integration and advanced climate visualization.\\n\\n**Repository**: [GitHub Link](https://github.com/sankalpjaiswal013-ops/Drought-Prediction)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.hephaestus,
    loadIndex: 71,
    purityIndex: 82,
    cyberMeshLevel: 5,
    archivist: "Sankalp Jaiswal",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-42",
    code: "PRJ-042",
    name: "SimpleV",
    description: "SimpleV is an open-source, local-first vector database designed for AI applications, Retrieval-Augmented Generation (RAG), and personal knowledge bases. Built with the vision of being the \"SQLite for Vector Search,\" it offers a zero-configuration, Python-first developer experience that completely removes the need for Docker, cloud accounts, or complex server setups.\\n\\n**Status**: The architectural design and planning phase is fully complete. The project vision, API specifications, storage/indexing engine mechanics, and roadmaps have been thoroughly laid out and documented across multiple Markdown files. This comprehensive documentation has just been pushed to the repository, and we are now actively transitioning into the development phase to start writing the core code.\\n\\n**Repository**: [GitHub Link](https://github.com/sushk2904/simplev)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.aristotle,
    loadIndex: 87,
    purityIndex: 78,
    cyberMeshLevel: 6,
    archivist: "Sushant Kumar",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-43",
    code: "PRJ-043",
    name: "Kishan GPT",
    description: "KisanGPT is an AI-powered multi-agent platform that helps farmers make smarter decisions using Gemini AI, weather intelligence, market insights, government scheme recommendations, financial risk analysis, and personalized action plans.\\n\\n**Status**: Some Agent work is remaining.\\n\\n**Repository**: [GitHub Link](https://github.com/PankajKumarYdv/KisanGPT)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.atlas,
    loadIndex: 47,
    purityIndex: 70,
    cyberMeshLevel: 6,
    archivist: "Pankaj Kumar",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-44",
    code: "PRJ-044",
    name: "UrbanMind",
    description: "UrbanMind is a realtime urban traffic intelligence platform built for hackathon demos, operator-facing command workflows, and AI-assisted mobility storytelling. It combines adaptive signal control, YOLO-based vision analysis, emergency green-corridor automation, live multi-node footage, GPS-aware emergency tracking, congestion rerouting guidance, and responsive digital twin and admin experiences into one coordinated system.\\n\\n**Status**: MVP\\n\\n**Repository**: [GitHub Link](https://github.com/Anurag-M1/UrbanMind)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.ares,
    loadIndex: 60,
    purityIndex: 85,
    cyberMeshLevel: 6,
    archivist: "Anurag Kumar Singh",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-45",
    code: "PRJ-045",
    name: "EchoMind - Mental Wellness Resource Architect",
    description: "EchoMind is a RAG-powered AI platform that synthesizes fragmented mental wellness information into trustworthy, actionable support paths for individuals in need. Built to solve the \"Information Fragmentation and Accessibility Gap\" in youth mental wellness resources.\\n\\n**Status**: You could describe the project status like this:  **Project Status:** EchoMind is currently in the **prototype/MVP development stage**. The core RAG (Retrieval-Augmented Generation) pipeline has been designed to retrieve and synthesize reliable mental wellness resources into personalized, actionable guidance. Initial work includes resource collection, knowledge base creation, and conversational AI integration. The platform is being tested for response accuracy, relevance, and accessibility, with future plans to expand trusted data sources, enhance personalization, and conduct user testing with young adults and mental health professionals.\\n\\n**Repository**: [GitHub Link](https://github.com/MariyaMomin/EchoMind)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.prometheus,
    loadIndex: 50,
    purityIndex: 78,
    cyberMeshLevel: 5,
    archivist: "Mariya Momin",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-46",
    code: "PRJ-046",
    name: "Physics-Edge-Cloud",
    description: "It's a 9-layer video anomaly detection framework that optimized the trade-off between real-time detection latency, cloud bandwidth costs, and strict privacy regulations by leveraging lightweight physics-based algorithms on sub-watt microcontroller edge device which filters 80-90 % of normal scene activity before it ever reaches the cloud.\\n\\n**Status**: In process\\n\\n**Repository**: [GitHub Link](https://github.com/Anshul-5/Physics-Edge-Cloud)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.neuralLattice,
    loadIndex: 44,
    purityIndex: 76,
    cyberMeshLevel: 6,
    archivist: "Anshul Panwar",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-47",
    code: "PRJ-047",
    name: "AI-Powered Emergency Green Traffic Corridor System",
    description: "An AI-powered traffic management system that automatically creates a green corridor for emergency vehicles such as ambulances and fire trucks. The system uses computer vision and AI-based traffic analysis to detect emergency vehicles, optimize routes, and dynamically control traffic signals to reduce response time during emergencies.\\n\\n**Status**: The project is currently in the planning and initial development phase. The core project structure, architecture, and repository have been created. The problem statement, objectives, and technology stack have been finalized, and initial modules for emergency vehicle detection and traffic signal management are being designed. During IEEE Summer of Code, contributors will implement AI-based vehicle detection, route optimization, adaptive traffic signal control, simulation, backend APIs, frontend dashboard, and system integration. The project welcomes contributors across AI/ML, Computer Vision, Backend, Frontend, DevOps, and Documentation.\\n\\n**Repository**: [GitHub Link](https://github.com/krishnachoudhary1969/AI-Emergency-Traffic-Corridor-System)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.gildedGuardian,
    loadIndex: 70,
    purityIndex: 94,
    cyberMeshLevel: 7,
    archivist: "Krishna Choudhary",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-48",
    code: "PRJ-048",
    name: "Campus Navigation",
    description: "CampusNav-AI is an intelligent campus navigation system that combines AI-powered pathfinding with a natural language chatbot to help users navigate indoor and outdoor campus locations. The project provides interactive maps, shortest-path routing using BFS and Dijkstra's algorithms, and an NLP-based chatbot that answers location-based queries using a live MySQL database. Built with React, Spring Boot, Python Flask, and MySQL, the system offers a modern, responsive interface for seamless campus navigation.\\n\\n**Status**: The project has a functional MVP with the core navigation system, interactive frontend, backend APIs, database integration, and AI chatbot already implemented. Current development focuses on enhancing the chatbot with LLM capabilities, improving navigation accuracy, optimizing performance, expanding campus data, strengthening testing, and improving documentation. During IEEE Summer of Code, contributors will work on feature enhancements, bug fixes, UI/UX improvements, AI integration, testing, and deployment.\\n\\n**Repository**: [GitHub Link](https://github.com/krishnachoudhary1969/Campus_Navigation)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.valerius,
    loadIndex: 57,
    purityIndex: 82,
    cyberMeshLevel: 6,
    archivist: "Krishna Choudhary",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-49",
    code: "PRJ-049",
    name: "OS LAB SIMULATOR",
    description: "OS Lab Simulator is an open-source, full-stack educational platform for learning and visualizing Operating System algorithms through interactive simulations. The project supports CPU Scheduling, Page Replacement, and Disk Scheduling algorithms with real-time visualizations, performance comparisons, execution traces, and detailed metrics. Built using React, FastAPI, Python, and Tailwind CSS, it provides students and educators with an intuitive environment to understand complex OS concepts through hands-on experimentation and algorithm analysis.\\n\\n**Status**: The project currently has a functional full-stack implementation with core algorithms, REST APIs, interactive visualizations, and a responsive frontend completed. Ongoing development focuses on adding new algorithms, improving visualization quality, enhancing performance, increasing test coverage, refining the user experience, expanding documentation, and integrating advanced educational features. During IEEE Summer of Code, contributors will work on feature enhancements, algorithm optimization, testing, UI/UX improvements, documentation, and deployment to make the simulator a comprehensive open-source learning platform.\\n\\n**Repository**: [GitHub Link](https://github.com/krishnachoudhary1969/OS_LAB_SIMULATOR)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.column,
    loadIndex: 33,
    purityIndex: 74,
    cyberMeshLevel: 7,
    archivist: "Krishna Choudhary",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-50",
    code: "PRJ-050",
    name: "ResearchForge",
    description: "ResearchForge is an open-source AI-powered research operating system designed to help researchers discover, organize, understand, and collaborate on scientific knowledge. It combines AI-assisted literature analysis, semantic search, knowledge graphs, citation-aware retrieval, collaborative workspaces, and research analytics into a modular platform. Built for researchers, students, and developers, ResearchForge aims to make scientific research more accessible, reproducible, and community-driven while providing an extensible ecosystem for open-source contributions.\\n\\n**Status**: ResearchForge is currently in the planning and architecture design phase. The project vision, scope, and modular architecture have been defined, and repository initialization is underway. The immediate milestones include establishing the project structure, contribution guidelines, documentation, and the MVP architecture for AI-powered research management. Development will begin with document ingestion, semantic search, AI summarization, and collaborative research workspaces before expanding into knowledge graphs, citation intelligence, and advanced research analytics. The project is being designed from the outset to support community contributions and long-term open-source growth.\\n\\n**Repository**: [GitHub Link](https://github.com/JanmejaiPratapTonk-123/ResearchForge)",
    category: "Architectural",
    imageUrl: ARTIFACT_IMAGES.castle,
    loadIndex: 47,
    purityIndex: 82,
    cyberMeshLevel: 9,
    archivist: "Janmejai Pratap Tonk",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-51",
    code: "PRJ-051",
    name: "AI Notifier",
    description: "AI Notifier: AI Notification Management System\\n\\n**Status**: The app is built and running smoothly with the local AI, and the code is up on GitHub.\\n\\n**Repository**: [GitHub Link](https://github.com/khanrehan00931-creator/AI-Notifier)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.athena,
    loadIndex: 56,
    purityIndex: 93,
    cyberMeshLevel: 8,
    archivist: "P. Abdul Rehan Khan",
    dateCreated: "2026-08-07"
  },
  {
    id: "prj-52",
    code: "PRJ-052",
    name: "NA",
    description: "NA\\n\\n**Status**: NA\\n\\n**Repository**: [GitHub Link](NA)",
    category: "Technical",
    imageUrl: ARTIFACT_IMAGES.socrates,
    loadIndex: 44,
    purityIndex: 90,
    cyberMeshLevel: 6,
    archivist: "Harivansh B",
    dateCreated: "2026-08-07"
  }
];
